name: Run Backend Server

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  run-server:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          cache: 'npm'

      - name: Install dependencies
        run: |
          cd server
          npm install

      - name: Start server
        run: |
          cd server
          npm start
        env:
          NODE_ENV: production
          PORT: 3001 